# Generated by Django 4.1.3 on 2023-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifi', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
