# Generated by Django 4.1.3 on 2023-01-31 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotifi', '0003_playlist_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spotifi.album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='music',
            name='style',
            field=models.ManyToManyField(related_name='music', to='spotifi.style'),
        ),
        migrations.AlterField(
            model_name='music',
            name='submitter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
