# Generated by Django 4.1.3 on 2023-01-31 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotifi', '0005_alter_album_submitter_alter_album_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='submitter',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
