# Generated by Django 4.1.3 on 2023-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifi', '0006_alter_album_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
