# Generated by Django 4.1.3 on 2023-02-03 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotifi', '0007_alter_album_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_music', to=settings.AUTH_USER_MODEL),
        ),
    ]
